name: KBOT-CICD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: make image push

      - name: Get Version
        id: get_version
        run: |
          version=$(make print-version)
          echo "Version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.ci.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update image tag in Helm cart
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
            yq -i '.appVersion = strenv(VERSION)' helm/Chart.yaml
            yq -i '.version = strenv(VERSION)' helm/Chart.yaml

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email github-actions@github.com
          git commit -am "Update image tag to $VERSION"
          git push

